const VERSION="9.0";
const DATA_KEY="bahnpreis_tracker_v9_preview";
const DRAFT_KEY="bahnpreis_tracker_v9_preview_drafts";
let state=null, currentDestination=null;
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function euro(v){return v==null||v===""?"–":new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(Number(v))}
function dateDE(v){if(!v)return"–";const[y,m,d]=v.split("-");return`${d}.${m}.${y}`}
function dateTime(v){if(!v)return"–";return new Intl.DateTimeFormat("de-DE",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function price(v){const s=String(v??"").replace(/\s/g,"").replace("€","").replace(",", ".");const n=Number(s);return Number.isFinite(n)?n:null}
async function load(){const x=localStorage.getItem(DATA_KEY);state=x?JSON.parse(x):await fetch("initial-data.json",{cache:"no-store"}).then(r=>r.json());save();render()}
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(state))}
function project(){return state.projects.find(p=>p.id===state.activeProjectId)||state.projects[0]}
function draftKey(p,r){return`${p.id}::${r.id}`}
function getDraft(p,r){try{return JSON.parse(localStorage.getItem(DRAFT_KEY)||"{}")[draftKey(p,r)]||null}catch{return null}}
function setDraft(p,r,v){let d={};try{d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"{}")}catch{}d[draftKey(p,r)]={...v,updatedAt:new Date().toISOString()};localStorage.setItem(DRAFT_KEY,JSON.stringify(d))}
function clearDraft(p,r){let d=JSON.parse(localStorage.getItem(DRAFT_KEY)||"{}");delete d[draftKey(p,r)];localStorage.setItem(DRAFT_KEY,JSON.stringify(d))}
function groups(p){const m=new Map();p.routes.forEach(r=>{if(!m.has(r.destination))m.set(r.destination,[]);m.get(r.destination).push(r)});return [...m.entries()]}
function latest(p,r){return(p.observations||[]).filter(o=>o.routeId===r.id).sort((a,b)=>Date.parse(b.queriedAt)-Date.parse(a.queriedAt))[0]||null}
function dbUrl(p,destination){const q=new URLSearchParams({SO:p.origin,ZO:destination,HD:`${p.travelDate}T06:00:00`,HZA:"D",AR:"false",S:"true",D:"false"});return`https://www.bahn.de/buchung/start#?${q}`}
function render(){const p=project();$("projectSelect").innerHTML=state.projects.map(x=>`<option value="${x.id}">${dateDE(x.travelDate)} · ${esc(x.origin)}</option>`).join("");$("travelDate").textContent=dateDE(p.travelDate);$("destinations").innerHTML=groups(p).map(([dest,rs])=>card(p,dest,rs)).join("");bind(p)}
function card(p,dest,rs){return`<article class="route-card"><div class="route-head"><div class="route-title"><span class="code">${esc(rs[0].code)}</span><h2>${esc(p.origin)} → ${esc(dest)}</h2></div><div class="card-buttons"><button class="db" data-db="${esc(dest)}">DB öffnen</button><button data-history="${esc(dest)}">Verlauf</button></div></div><div class="window-grid">${rs.map(r=>{const x=getDraft(p,r)||latest(p,r);return`<div class="window-row"><div class="window-name">${r.slotLabel}</div><div class="window-value ${x?'':'empty'}">${x?`${esc(x.train||r.train||'Zug offen')} · ${esc(x.time||r.time)}`:'noch nicht erfasst'}</div><div class="window-value">${x?`${euro(x.superPrice)} / ${euro(x.saverPrice)}`:'–'}</div><div class="window-value">${x?esc(x.load||'Auslastung –'):'–'}</div></div>`}).join("")}</div><button class="import-btn" data-import="${esc(dest)}">3 Verbindungen erfassen und prüfen</button>${rs.some(r=>getDraft(p,r))?'<div class="checked">✓ geprüfte Werte warten auf „Abfrage abschließen“</div>':''}</article>`}
function bind(p){document.querySelectorAll('[data-db]').forEach(b=>b.onclick=()=>window.open(dbUrl(p,b.dataset.db),'_blank','noopener,noreferrer'));document.querySelectorAll('[data-import]').forEach(b=>b.onclick=()=>openImport(p,b.dataset.import));document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>showHistory(p,b.dataset.history))}
function openImport(p,dest){currentDestination=dest;$("importTitle").textContent=dest;const rs=p.routes.filter(r=>r.destination===dest);$("reviewRows").innerHTML=rs.map(r=>{const x=getDraft(p,r)||latest(p,r)||{};return`<div class="review-row" data-review="${r.id}"><div class="slot">${r.slotLabel}</div><div class="review-fields"><label>Abfahrt<input data-time value="${esc(x.time||r.time||'')}"></label><label>Zug<input data-train value="${esc(x.train||r.train||'')}"></label><label>Super Sparpreis<input data-super inputmode="decimal" value="${esc(String(x.superPrice??'').replace('.',','))}"></label><label>Sparpreis<input data-saver inputmode="decimal" value="${esc(String(x.saverPrice??'').replace('.',','))}"></label><label>Auslastung<select data-load><option value="">–</option>${['gering','mittel','hoch','sehr hoch','ausgebucht'].map(v=>`<option ${x.load===v?'selected':''}>${v}</option>`).join('')}</select></label></div></div>`}).join('');$("ocrStatus").textContent="Noch kein Screenshot ausgewählt.";$("importDialog").showModal()}
function parseCandidates(text){const lines=String(text).split(/\n+/).map(x=>x.trim()).filter(Boolean);const out=[];for(let i=0;i<lines.length;i++){const area=lines.slice(Math.max(0,i-2),Math.min(lines.length,i+7)).join(' ');const tm=area.match(/\b([0-2]?\d[:.]\d{2})\b/);const tr=area.match(/\b(ICE|IC|EC|RE|RB)\s*\d{1,4}\b/i);const ps=[...area.matchAll(/(\d{1,3}[,.]\d{2})\s*€/g)].map(m=>m[1]);if(tm&&ps.length){const t=tm[1].replace('.',':');if(!out.some(x=>x.time===t))out.push({time:t,train:tr?tr[0].toUpperCase().replace(/\s+/,' '):'',superPrice:ps[0],saverPrice:ps[1]||'',load:(area.toLowerCase().match(/ausgebucht|sehr hoch|hoch|mittel|gering/)||[''])[0]})}}
return out.sort((a,b)=>a.time.localeCompare(b.time))}
function assignCandidates(cands){const rows=[...document.querySelectorAll('[data-review]')];const targets=[9*60,13*60,18*60];const used=new Set();rows.forEach((row,i)=>{let best=-1,dist=1e9;cands.forEach((c,j)=>{if(used.has(j))return;const[h,m]=c.time.split(':').map(Number);const d=Math.abs(h*60+m-targets[i]);if(d<dist){dist=d;best=j}});if(best<0)return;used.add(best);const c=cands[best];row.querySelector('[data-time]').value=c.time;row.querySelector('[data-train]').value=c.train;row.querySelector('[data-super]').value=c.superPrice;row.querySelector('[data-saver]').value=c.saverPrice;row.querySelector('[data-load]').value=c.load||''})}
$("chooseShots").onclick=()=>$("multiShotInput").click();
$("multiShotInput").onchange=async e=>{const files=[...e.target.files];if(!files.length)return;$("ocrStatus").textContent=`${files.length} Screenshot(s) werden gelesen …`;let all=[];try{for(let i=0;i<files.length;i++){const r=await Tesseract.recognize(files[i],'deu');all=all.concat(parseCandidates(r.data.text));$("ocrStatus").textContent=`Screenshot ${i+1} von ${files.length} gelesen …`}assignCandidates(all);$("ocrStatus").textContent=`${all.length} mögliche Verbindung(en) erkannt. Bitte alle Werte prüfen.`}catch{$("ocrStatus").textContent='OCR fehlgeschlagen. Du kannst die Werte trotzdem manuell eintragen.'}e.target.value=''};
$("acceptImport").onclick=()=>{const p=project();document.querySelectorAll('[data-review]').forEach(row=>{const r=p.routes.find(x=>x.id===row.dataset.review);setDraft(p,r,{time:row.querySelector('[data-time]').value,train:row.querySelector('[data-train]').value,superPrice:row.querySelector('[data-super]').value,saverPrice:row.querySelector('[data-saver]').value,load:row.querySelector('[data-load]').value})});$("importDialog").close();render();$("globalStatus").textContent=`${currentDestination}: geprüfte Werte übernommen, aber noch nicht in der Historie gespeichert.`};
$("cancelImport").onclick=()=>$("importDialog").close();$("closeImport").onclick=()=>$("importDialog").close();
$("completeBtn").onclick=()=>{const p=project(),now=new Date().toISOString();let n=0;p.routes.forEach(r=>{const d=getDraft(p,r);if(!d)return;const sp=price(d.superPrice),sa=price(d.saverPrice);if(sp==null&&sa==null)return;p.observations.push({id:uid(),queriedAt:now,travelDate:p.travelDate,routeId:r.id,code:r.code,origin:p.origin,destination:r.destination,slot:r.slot,slotLabel:r.slotLabel,time:d.time,train:d.train,superPrice:sp,saverPrice:sa,price:[sp,sa].filter(x=>x!=null).sort((a,b)=>a-b)[0]??null,fareType:sp!=null?'Super Sparpreis':'Sparpreis',load:d.load||'',note:'kontrollierter Mehrfachimport'});r.time=d.time;r.train=d.train;clearDraft(p,r);n++});p.updatedAt=now;save();render();$("globalStatus").textContent=n?`${n} geprüfte Verbindungen gespeichert.`:'Keine geprüften Werte vorhanden.'};
$("backupBtn").onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString(),version:9},null,2)],{type:'application/json'}));a.download=`bahnpreis_tracker_v9_${new Date().toISOString().slice(0,10)}.json`;a.click()};
$("restoreBtn").onclick=()=>$("restoreInput").click();$("restoreInput").onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.projects))throw 0;state=x;save();render();$("globalStatus").textContent='Backup wiederhergestellt.'}catch{$("globalStatus").textContent='Backup nicht lesbar.'}e.target.value=''};
function showHistory(p,dest){const rows=(p.observations||[]).filter(o=>o.destination===dest).sort((a,b)=>Date.parse(b.queriedAt)-Date.parse(a.queriedAt));$("historyTitle").textContent=`${dest} · Verlauf`;$("historyTable").innerHTML=rows.length?`<table><thead><tr><th>Abfrage</th><th>Zeitfenster</th><th>Zug</th><th>Abfahrt</th><th>Super</th><th>Spar</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${dateTime(o.queriedAt)}</td><td>${esc(o.slotLabel||o.slot||'')}</td><td>${esc(o.train||'')}</td><td>${esc(o.time||'')}</td><td>${euro(o.superPrice)}</td><td>${euro(o.saverPrice)}</td></tr>`).join('')}</tbody></table>`:'Noch keine Daten.';$("historyDialog").showModal()}
$("closeHistory").onclick=()=>$("historyDialog").close();
$("projectSelect").onchange=e=>{state.activeProjectId=e.target.value;save();render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');load();
